FROM mcr.microsoft.com/dotnet/aspnet:8.0  AS base
COPY bin/Release/net8.0/publish/ app/
WORKDIR /app

FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src
RUN dotnet dev-certs https -v -ep openiddict.pfx -p 4aa969f4-f84a-45a9-859f-b6e9256022d4

FROM base AS final
WORKDIR /app
COPY --from=build /src .

ENTRYPOINT ["dotnet", "PlayGround.HttpApi.Host.dll"]